### ISSUE TITLE
Airflow docker is not getting Up after adding the instruction

### ISSUE THREAD

**Issue by NonlinearNimesh** [newrelic/newrelic-airflow-plugin#33]
Hi, 
I wanted to monitor airflow with neurelic but when i added these below thing, docker it not getting up
```
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.3.3}
  # build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__PARALLELISM: 16
    AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 32
    AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 16 #  number of dag run basically Number of vertical lines
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'true'
    NEW_RELIC_INSERT_KEY: 'added newrelic licence key'               
    NEW_RELIC_SERVICE_NAME : 'airflow'
    NEW_RELIC_HOST : 'metric-api.eu.newrelic.com'
    AIRFLOW__CORE__LAZY_LOAD_PLUGINS='false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:- newrelic-airflow-plugin}

```

Can anyone help me what i am doing wrong here.

Thanks
